{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-feature-classifier
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-learn {{ scikit_learn }}
    - joblib
    - scikit-bio {{ scikit_bio }}
    - biom-format {{ biom_format }}
    - blast >=2.6.0
    - vsearch
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-quality-control {{ qiime2_epoch }}.*
    - q2-taxa {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2-quality-control >={{ q2_quality_control }}
    - q2-taxa >={{ q2_taxa }}
    - q2-feature-table >={{ q2_feature_table }}
    - pytest

  imports:
    - q2_feature_classifier
    - qiime2.plugins.feature_classifier

  commands:
    - py.test --pyargs q2_feature_classifier

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
