{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-feature-classifier
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-learn 0.21.2
    - joblib
    - scikit-bio
    - biom-format >=2.1.5,<2.2.0
    - blast >=2.6.0
    # There are issues with 2.8.2, and no OS X builds exist after 2.7.0
    - vsearch <=2.7.0
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - q2-quality-control {{ release }}.*
    - q2-taxa {{ release }}.*
    - q2-feature-table {{ release }}.*

test:
  imports:
    - q2_feature_classifier
    - qiime2.plugins.feature_classifier

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
